<a href="https://colab.research.google.com/github/matiasdemori/Trabajo-Integrador-Ciencia-de-Datos/blob/main/TP_Integrados_Ciencia_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TRABAJO PRÁCTICO GRUPAL INTEGRADOR
*Unidad:* 1 y 2

*Materia:* Ciencia de Datos  


---


*Fecha Entrega 1:* 27/04/2026

*Fecha Entrega 2:* 11/05/2026

### Integrantes del grupo:
* Franco Lavirgen
* Matias De Mori
* Juan Cruz Palacio Hernandez
* Angelo Grammatico

### Docentes:
* Germán Giró
* Malena Constancio
* Giselle Bustamante

# 1ra Entrega
En esta primera entrega buscamos definir el problema que vamos a analizar, comprender el contexto del proyecto y realizar una exploración inicial del dataset seleccionado siguiendo las primeras etapas de la metodología CRISP-DM. Además, planteamos nuestras preguntas analíticas principales, justificamos la elección del dataset y evaluamos de manera preliminar la estructura y calidad de los datos con los que vamos a trabajar.

##Comprensión del negocio


### Contexto
El precio de los combustibles representa una variable de gran impacto dentro de la economía argentina, ya que influye directamente en los costos de transporte, logística, producción y distribución de bienes y servicios. Además, las variaciones de precios afectan tanto a consumidores particulares como a empresas y actividades comerciales en distintas regiones del país.
Debido a esto, resulta relevante analizar cómo se comportan los precios de los combustibles según distintos factores como la ubicación geográfica, la empresa comercializadora y el tipo de producto ofrecido.

###Problema
Si bien existe información pública y actualizada sobre precios de combustibles en estaciones de servicio de Argentina, el volumen de datos y la frecuencia de actualización dificultan la identificación de patrones claros sin un análisis previo.
El problema principal consiste en comprender qué factores explican las diferencias de precios observadas en el mercado y determinar si ciertas brechas de precios se mantienen estables en el tiempo o presentan fluctuaciones significativas.

###Objetivos
<u>_Objetivo principal_</u>

- Analizar en qué medida el factor geográfico, la bandera comercial y el tipo de combustible influyen en la variabilidad de los precios promedio semanales en Argentina durante los últimos 12 meses.

<u>_Objetivos secundarios_</u>


- Comparar precios promedio semanales entre provincias.
- Analizar la dispersión de precios entre distintas empresas comercializadoras.
- Evaluar diferencias de precios entre tipos de combustible.
- Detectar regiones o empresas con precios sistemáticamente más altos o más bajos.
- Observar la estabilidad o fluctuación de las brechas de precios a lo largo del período analizado.

### Preguntas a Analizar

<u>_Pregunta analítica principal_</u>

- ¿En qué medida el factor geográfico, la bandera comercial y el tipo de producto explican la variabilidad de los precios semanales en Argentina, y qué tan estables se mantienen las brechas de mercado entre estos segmentos a lo largo del último año?

<u>_Preguntas analíticas secundarias_</u>

Segmentación geográfica

- ¿Qué provincias presentan precios promedio semanales por encima de la media nacional y qué tan amplia es la brecha entre la región más cara y la más barata?

Competencia entre empresas

- ¿Cómo varía la dispersión de los precios promedio semanales entre las diferentes empresas del sector, y qué proporción de marcas mantienen precios por encima de la mediana nacional de forma constante?

Análisis por tipo de combustible

- ¿Cuál es la magnitud de la brecha de precio entre los distintos tipos de combustible (Premium vs. Súper) y cómo ha fluctuado esta diferencia porcentual en el promedio semanal de los últimos 12 meses?

<u>_Alcance del análisis_</u>

Para mantener un alcance adecuado al trabajo práctico, se decidió trabajar únicamente con:

- Los últimos 12 meses disponibles del dataset.
- Precios promedio semanales en lugar de registros horarios.
- Las variables: provincia, empresa, fecha, precio y tipo de combustible.

Este recorte permite reducir el volumen de datos, disminuir ruido generado por actualizaciones frecuentes y enfocarse en tendencias y diferencias relevantes para el análisis.

<u>_Criterios de éxito_</u>

Se considerará exitoso el proyecto si se logra:

- Identificar diferencias significativas de precios entre provincias, empresas y tipos de combustible.
- Detectar patrones consistentes o fluctuaciones relevantes en el tiempo.
- Construir visualizaciones que permitan interpretar claramente los resultados.

##Comprensión de los datos

###Dataset seleccionado

- Precios en Surtidor – Resolución 314/2016
Fuente oficial: Portal de Datos Abiertos de la República Argentina.

- Contiene información sobre precios de combustibles relevados en estaciones de servicio del país.

El conjunto de datos posee una cantidad muy elevada de registros, ya que contiene información histórica desde años anteriores y actualizaciones frecuentes. Por este motivo, trabajar la base completa excede el alcance del trabajo práctico.

<u>_**Recorte definido para el análisis**_</u>

Para hacer el proyecto manejable y enfocado, se decidió trabajar con:

- Los últimos 12 meses disponibles del dataset.
- Precio promedio semanal como unidad de análisis.

Esto permite reducir el volumen de datos, disminuir ruido generado por actualizaciones horarias y enfocarse en tendencias recientes.

###3.1.B Comprensión de los datos (Data Understanding)
<u>_**Dataset seleccionado**_</u>

- Precios en Surtidor – Resolución 314/2016
Fuente oficial: Portal de Datos Abiertos de la República Argentina.

- Contiene información sobre precios de combustibles relevados en estaciones de servicio del país.

<u>_**Tipo de información disponible**_</u>

El dataset incluye variables como:

- Fecha de actualización.
- Empresa o bandera comercial.
- Provincia.
- Localidad.
- Dirección.
- Tipo de combustible.
- Precio informado.
- Latitud y longitud.
- Volumen de datos

El conjunto de datos posee una cantidad muy elevada de registros, ya que contiene información histórica desde años anteriores y actualizaciones frecuentes. Por este motivo, trabajar la base completa excede el alcance del trabajo práctico.

<u>_**Recorte definido para el análisis**_</u>

Para hacer el proyecto manejable y enfocado, se decidió trabajar con:

- Los últimos 12 meses disponibles del dataset.
- Precio promedio semanal como unidad de análisis.

Esto permite reducir el volumen de datos, disminuir ruido generado por actualizaciones horarias y enfocarse en tendencias recientes.

<u>_**Calidad de datos esperada**_</u>

Al tratarse de datos reales provenientes de múltiples estaciones, es posible encontrar:

- Valores faltantes.
- Registros duplicados.
- Diferencias en nombres de localidades o marcas.
- Valores atípicos o inconsistentes.
- Errores de formato en fechas o precios.
- Primeras tareas previstas
- Limpieza y depuración de registros.
- Conversión de fechas y precios a formatos adecuados.
- Filtrado temporal.
- Agrupación semanal.
- Validación de valores extremos.

El dataset seleccionado es “Precios en Surtidor – Resolución 314/2016”, disponible en el portal oficial de Datos Abiertos de la República Argentina (datos.gob.ar). Este conjunto de datos reúne información sobre los precios de venta de combustibles informados por estaciones de servicio de distintas provincias del país, incluyendo variables como fecha de actualización, empresa comercializadora, ubicación geográfica, tipo de combustible y precio registrado.

Se trata de una base de datos pública, real y de actualización periódica, lo que la convierte en una fuente confiable y relevante para realizar análisis. Entre sus principales cualidades se destacan la gran cantidad de registros disponibles, la diversidad de variables temporales, geográficas y numéricas, y la posibilidad de estudiar tendencias, comparaciones regionales y evolución de precios a lo largo del tiempo.

Este dataset se ajusta a lo solicitado por la cátedra porque supera ampliamente el mínimo de registros requerido, posee múltiples columnas con información útil para el análisis y presenta desafíos reales de limpieza, transformación y exploración de datos. Además, permite aplicar de forma adecuada la metodología CRISP-DM, trabajando tanto la comprensión del negocio como el análisis de datos sobre una problemática actual y relevante en la economía argentina.

El dataset fue validado con la catedra con la sugerencia de acotar la cantidad de registros debido a su gran tamaño, es por ello que mas adelante realizaremos un ajuste sobre esto en funcion de los objetivos planteados.

In [ ]:
# Importacion de librerias necesarias
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request

In [ ]:
# Guardamos en una variable la URL donde está el archivo CSV
url = "http://datos.energia.gob.ar/dataset/1c181390-5045-475e-94dc-410429be4b17/resource/f8dda0d5-2a9f-4d34-b79b-4e63de3995df/download/precios-historicos.csv"

# Leemos el archivo CSV desde la URL y lo carga en un DataFrame llamado df
df = pd.read_csv(url)

In [ ]:
# Muestramos las primeras 5 filas del dataset
df.head()

,idempresa,empresa,direccion,localidad,provincia,idproducto,producto,idtipohorario,tipohorario,precio,fecha_vigencia,idempresabandera,empresabandera,latitud,longitud,geojson,anio,mes
0,1376,10 DE SETIEMBRE S.A.,Av. Mosconi 299,LOMAS DEL MIRADOR,BUENOS AIRES,19,Gas Oil Grado 2,2,Diurno,985.0,01/04/2024 10:11,28,PUMA,-34.658476,-58.529443,"{""type"":""Point"",""coordinates"":[-58.529443,-34....",2024,4
1,1376,10 DE SETIEMBRE S.A.,Av. Mosconi 299,LOMAS DEL MIRADOR,BUENOS AIRES,19,Gas Oil Grado 2,3,Nocturno,985.0,01/04/2024 10:11,28,PUMA,-34.658476,-58.529443,"{""type"":""Point"",""coordinates"":[-58.529443,-34....",2024,4
2,1376,10 DE SETIEMBRE S.A.,Av. Mosconi 299,LOMAS DEL MIRADOR,BUENOS AIRES,19,Gas Oil Grado 2,2,Diurno,1080.0,01/07/2024 09:43,28,PUMA,-34.658476,-58.529443,"{""type"":""Point"",""coordinates"":[-58.529443,-34....",2024,7
3,1376,10 DE SETIEMBRE S.A.,Av. Mosconi 299,LOMAS DEL MIRADOR,BUENOS AIRES,19,Gas Oil Grado 2,3,Nocturno,1080.0,01/07/2024 09:43,28,PUMA,-34.658476,-58.529443,"{""type"":""Point"",""coordinates"":[-58.529443,-34....",2024,7
4,1376,10 DE SETIEMBRE S.A.,Av. Mosconi 299,LOMAS DEL MIRADOR,BUENOS AIRES,19,Gas Oil Grado 2,2,Diurno,1108.0,01/08/2024 13:40,28,PUMA,-34.658476,-58.529443,"{""type"":""Point"",""coordinates"":[-58.529443,-34....",2024,8

In [ ]:
# Miramos un resumen general del dataset:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337283 entries, 0 to 3337282
Data columns (total 18 columns):
 #   Column            Dtype
---  ------            -----
 0   idempresa         int64
 1   empresa           object
 2   direccion         object
 3   localidad         object
 4   provincia         object
 5   idproducto        int64
 6   producto          object
 7   idtipohorario     int64
 8   tipohorario       object
 9   precio            float64
 10  fecha_vigencia    object
 11  idempresabandera  int64
 12  empresabandera    object
 13  latitud           float64
 14  longitud          float64
 15  geojson           object
 16  anio              int64
 17  mes               int64
dtypes: float64(3), int64(6), object(9)
memory usage: 458.3+ MB

In [ ]:
# Vemos el tamaño de los datos
df.shape

(3337283, 18)

In [ ]:
# Muestramos los nombres de todas las columnas del dataset
df.columns

Index(['idempresa', 'empresa', 'direccion', 'localidad', 'provincia',
       'idproducto', 'producto', 'idtipohorario', 'tipohorario', 'precio',
       'fecha_vigencia', 'idempresabandera', 'empresabandera', 'latitud',
       'longitud', 'geojson', 'anio', 'mes'],
      dtype='object')

In [ ]:
# Contamos la cantidad de valores nulos (vacíos) por columna
df.isnull().sum()

idempresa              0
empresa                0
direccion              0
localidad              0
provincia              0
idproducto             0
producto               0
idtipohorario          0
tipohorario            0
precio                 0
fecha_vigencia         0
idempresabandera       0
empresabandera         0
latitud             1462
longitud            1462
geojson             1462
anio                   0
mes                    0
dtype: int64

In [ ]:
# Generamos algunas estadísticas descriptivas de las columnas numéricas:
df.describe()

,idempresa,idproducto,idtipohorario,precio,idempresabandera,latitud,longitud,anio,mes
count,3.337283e+06,3.337283e+06,3.337283e+06,3.337283e+06,3.337283e+06,3.335821e+06,3.335821e+06,3.337283e+06,3.337283e+06
mean,5.071893e+03,1.099436e+01,2.499988e+00,4.553325e+02,9.467368e+00,-3.352570e+01,-6.147711e+01,2.021442e+03,6.442716e+00
std,3.196741e+03,8.636939e+00,5.000001e-01,2.723872e+03,1.092330e+01,4.097164e+00,3.621863e+00,1.666924e+01,3.630445e+00
min,1.300000e+01,2.000000e+00,2.000000e+00,0.000000e+00,-1.000000e+00,-5.482950e+01,-7.233893e+01,1.000000e+00,1.000000e+00
25%,2.065000e+03,3.000000e+00,2.000000e+00,4.699000e+01,2.000000e+00,-3.479213e+01,-6.423593e+01,2.019000e+03,3.000000e+00
50%,4.851000e+03,6.000000e+00,2.000000e+00,1.362000e+02,4.000000e+00,-3.432265e+01,-6.056716e+01,2.022000e+03,6.000000e+00
75%,7.932000e+03,1.900000e+01,3.000000e+00,8.560000e+02,2.600000e+01,-3.146485e+01,-5.853706e+01,2.024000e+03,1.000000e+01
max,1.145300e+04,2.100000e+01,3.000000e+00,2.430000e+06,3.000000e+01,-2.205582e+01,-5.364826e+01,9.920000e+03,1.200000e+01

###3.1.C Justificación de la elección del dataset

Se eligió este dataset porque reúne características muy adecuadas para un proyecto introductorio de Ciencia de Datos.

<u>_**Motivos principales**_</u>

**Relevancia práctica**

- El precio de los combustibles es un tema actual que impacta en transporte, inflación, costos logísticos y economía cotidiana. Esto hace que el análisis tenga utilidad real.

**Cantidad de datos**

- Dispone de una base amplia, con suficientes registros para realizar análisis consistentes y obtener conclusiones respaldadas por evidencia.

**Diversidad de variables**

<u>Combina variables como:</u>

- Temporales (fecha).
- Geográficas (provincia, localidad, coordenadas).
- Categóricas (empresa, combustible).
- Numéricas (precio).

Esto permite aplicar distintas herramientas estadísticas y visuales.

**Posibilidad de análisis múltiples**

El dataset habilita trabajar con:

- Series temporales.
- Comparaciones regionales.
- Rankings.
- Detección de anomalías.
- Tendencias de mercado.

Permite aplicar correctamente las primeras etapas de la metodología CRISP-DM: comprensión del negocio, comprensión de los datos, preparación y análisis exploratorio.